# Generated by Django 4.1.1 on 2022-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
                ('cr', models.CharField(max_length=200)),
                ('classteachername', models.CharField(max_length=200)),
            ],
        ),
    ]
