# Generated by Django 4.1.1 on 2022-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_softwaresmodel_rename_schoolmodel_schoolsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cricketername', models.CharField(max_length=200)),
                ('coachname', models.CharField(max_length=200)),
                ('cr', models.CharField(max_length=200)),
                ('crcoachanushka', models.CharField(max_length=200)),
            ],
        ),
    ]
