# Generated by Django 4.1.1 on 2022-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_cricketersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('subject', models.IntegerField(choices=[(1, 'c'), (2, 'java'), (3, 'python')], default=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Schoolsname', models.CharField(max_length=200)),
                ('Section', models.CharField(max_length=200)),
                ('Cr', models.CharField(max_length=200)),
                ('Classteachername', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='SchoolsModel',
        ),
    ]
