# Generated by Django 4.1.1 on 2022-09-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_booksmodel_schoolmodel_statesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=220)),
            ],
        ),
    ]
